### ISSUE TITLE
Use mirror url in provider source

### ISSUE THREAD

**Issue by JBallin** [hashicorp/terraform-registry-address#17]
When setting a provider's `source` url to the artifactory registry mirror I receive this validation error:
> The “source” attribute must be in the format “[hostname/][namespace/]name”

How can I bypass the validation?

The api artifactory url is:
`https://instance-name.company-name.com/artifactory/api/terraform/virtual-repository-name/providers/"`

Example url I've tried (although I haven't been able to confirm it works properly, due to the validation error):
`instance-name.company-name.com/virtual-repository-name/newrelic/newrelic`

**Comment by radeksimko** [comment]
Hi @JBallin 
I am not familiar with Artifactory (or at least not its own implementation of the Registry protocol) and this sounds more like a question of the right address, rather than a bug. Provider addresses generally always have the three parts as mentioned in the error message.

Aside from asking jFrog/Artifactory I can recommend asking in our Discourse https://discuss.hashicorp.com/c/terraform-core/27

With that in mind I'm going to close this issue as it's not addressable here in this repository. Thanks for understanding.
